apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    argocd/app-name: ${{values.component_id}}-dev
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/kubernetes-namespace: ${{values.component_id}}-dev
    backstage.io/techdocs-ref: url:https://github.com/${{values.githubOrg}}/${{values.repoName}}
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: ${{values.destination}}
    quay.io/repository-slug: ${{values.quay_destination | dump}}
  
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces${{values.cluster}}/#https://github.com/${{values.destination}}?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces${{values.cluster}}/#https://github.com/${{values.destination}}?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  providesApis:
    - ${{values.component_id | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
spec:
  type: openapi
  lifecycle: production
  owner: ${{values.owner | dump}}
  definition:
    $text: ./openapi.yaml
