site_name: ${{values.component_id}}
site_description: ${{values.description}}
repo_url: https://github.com/${{values.destination}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Onboard a developer to OpenShift: onboard-openshift.md
