apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: quarkus-service-github-actions
  title: Quarkus Service with ArgoCD and GitHub Action Pipeline
  description: Create a simple microservice using Quarkus with ArgoCD and GitHub Action
  tags:
    - java
    - quarkus
    - maven
    - ghaction
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Provide information about the new component
      required:
        - githubOrg
        - repoName
        - owner
        - system
        - port
      properties:
        githubOrg:
          title: GitHub Organization
          type: string
          default: idp-myocp
        repoName:
          title: Repository Name
          type: string
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        port:
          title: Port
          type: number
          default: 8080
          description: Override the port exposed for the application
    - title: Provide information about the Java metadata
      required:
        - groupId
        - artifactId
        - javaPackageName
      properties:
        groupId:
          title: Group ID
          type: string
          default: io.janus
          description: Maven Group ID eg (io.janus)
        artifactId:
          title: Artifact ID
          type: string
          default: quarkusapp
          description: Maven Artifact ID
        javaPackageName:
          title: Java Package Namespace
          type: string
          default: io/janus/quarkusapp
          description: Name for the Java Package (ensure to use the / character as this is used for folder structure) should match Group ID and Artifact ID
    - title: Provide information about the Continuous Integration
      required:
        - ci
        - repoUrl
      properties:
        ci:
          title: Continuous Integration
          type: string
          description: This action will create a CI pipeline for your application based on GitHub Action
          default: GitHub Action
        image_registry:
          title: Image Registry
          type: string
          description: The image registry where the image will be store
          default: Artifactory
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:

    - id: sleep
      name: sleep 2 seconds
      action: roadiehq:utils:sleep
      input: 
        path: 2
           

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}