name: Promote to PreProd

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      #- '[0-9]+.[0-9]+.[0-9]+'
      - 'preprod'

jobs:
  tag-promote:
    runs-on: ubuntu-latest
    
    steps:
    - name: Search latest Image
      uses: tinact/docker.image-retag@master
      with:
        image_name: ${{ github.event.repository.name }}
        image_old_tag: latest
        image_new_tag: preprod
        registry: ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NAMESPACE }}
        registry_username: ${{ secrets.JF_USERNAME }}
        registry_password: ${{ secrets.JF_PASSWORD }}