name: Promote to PreProd

env:
  APP_NAME:  ${{ github.event.repository.name }}

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      #- '[0-9]+.[0-9]+.[0-9]+'
      - 'preprod'

jobs:
  tag-promote:
    runs-on: ubuntu-latest
    
    steps:
    - name: Search latest Image
      uses: tinact/docker.image-retag@master
      with:
        image_name: ${{ env.APP_NAME }}
        image_old_tag: latest
        image_new_tag: preprod
        registry: ${{ secrets.NEXUS_URL }}
        registry_username: ${{ secrets.NEXUS_USER }}
        registry_password: ${{ secrets.NEXUS_PASSWORD }}