apiVersion: backstage.io/v1alpha1
{%- if values.entityKind %}
kind: ${{ values.entityKind }}
{%- else %}
kind: Component
{%- endif %}
metadata:
  name: ${{ values.repoName }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    {%- if values.hostUrl %}
    argocd/app-name: ${{ values.repoName }}
    {%- endif %}
    backstage.io/kubernetes-id: ${{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.githubOrg }}/${{ values.repoName }}
    jira/project-key: ISSUEBD
    jfrog-artifactory/image-name: ${{ values.repoName }}

  tags:
    - java
    - quarkus
    - gh-action
    - artifactory
    - argocd
  links:
    - url: https://devspaces${{values.cluster}}/#https://github.com/${{values.githubOrg}}/${{values.repoName}}?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces${{values.cluster}}/#https://github.com/${{values.githubOrg}}/${{values.repoName}}?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web

spec:
  type: ${{ values.applicationType }}
  system: ${{ values.system }}
  lifecycle: production
  owner: ${{ values.owner }}
  {%- if values.dependsOn %}
  dependsOn:
    - ${{ values.dependsOn }}
  {%- endif %}
  {%- if values.partOf %}
  partOf:
    - ${{ values.partOf }}
  {%- endif %}