apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ${{ values.repoName }}-run-pipeline
  namespace: ${{ values.namespace }}
spec:
  params:
    - name: git-revision
      description: The git revision
      default: main
    - name: git-repo-url
      description: The repo url
    - name: output-image
      description: reference of the image that will get created
      default: ${{ values.imageRepository }}/${{ values.imageUrl }}/${{ values.repoName }}
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: ${{ values.repoName }}-pipeline-$(uid)
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-branch
            value: $(tt.params.git-revision)
          - name: output-image
            value: $(tt.params.output-image)
        pipelineRef:
          name: ${{ values.repoName }}-pipeline
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: source-folder
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
